export const district = [
  'Kennedy Town',
  'Shek Tong Tsui',
  'Sai Ying Pun',
  'Sheung Wan',
  'Central',
  'Admiralty',
  'Mid-levels',
  'Peak',
  'Wan Chai',
  'Causeway Bay',
  'Happy Valley',
  'Tai Hang',
  'So Kon Po',
  "Jardine's Lookout",
  'Tin Hau',
  'Braemar Hill',
  'North Point',
  'Quarry Bay',
  'Sai Wan Ho',
  'Shau Kei Wan',
  'Chai Wan',
  'Siu Sai Wan',
  'Pok Fu Lam',
  'Aberdeen',
  'Ap Lei Chau',
  'Wong Chuk Hang',
  'Shouson Hill',
  'Repulse Bay',
  'Chung Hom Kok',
  'Stanley',
  'Tai Tam',
  'Shek O',
  'Tsim Sha Tsui',
  'Yau Ma Tei',
  'West Kowloon Reclamation',
  "King's Park",
  'Mong Kok',
  'Tai Kok Tsui',
  'Mei Foo',
  'Lai Chi Kok',
  'Cheung Sha Wan',
  'Sham Shui Po',
  'Shek Kip Mei',
  'Yau Yat Tsuen',
  'Tai Wo Ping',
  'Stonecutters Island',
  'Hung Hom',
  'To Kwa Wan',
  'Ma Tau Kok',
  'Ma Tau Wai',
  'Kai Tak',
  'Kowloon City',
  'Ho Man Tin',
  'Kowloon Tong',
  'Beacon Hill',
  'San Po Kong',
  'Wong Tai Sin',
  'Tung Tau',
  'Wang Tau Hom',
  'Lok Fu',
  'Diamond Hill',
  'Tsz Wan Shan',
  'Ngau Chi Wan',
  'Ping Shek',
  'Kowloon Bay',
  'Ngau Tau Kok',
  'Jordan Valley',
  'Kwun Tong',
  'Sau Mau Ping',
  'Lam Tin',
  'Yau Tong',
  'Lei Yue Mun',
  'Kwai Chung',
  'Tsing Yi',
  'Tsuen Wan',
  'Lei Muk Shue',
  'Ting Kau',
  'Sham Tseng',
  'Tsing Lung Tau',
  'Ma Wan',
  'Sunny Bay',
  'Tai Lam Chung',
  'So Kwun Wat',
  'Tuen Mun',
  'Lam Tei',
  'Hung Shui Kiu',
  'Ha Tsuen',
  'Lau Fau Shan',
  'Tin Shui Wai',
  'Yuen Long',
  'San Tin',
  'Lok Ma Chau',
  'Kam Tin',
  'Shek Kong',
  'Pat Heung',
  'Fanling',
  'Luen Wo Hui',
  'Sheung Shui',
  'Shek Wu Hui',
  'Sha Tau Kok',
  'Luk Keng',
  'Wu Kau Tang',
  'Tai Po Market',
  'Tai Po',
  'Tai Po Kau',
  'Tai Mei Tuk',
  'Shuen Wan',
  'Cheung Muk Tau',
  'Kei Ling Ha',
  'Tai Wai',
  'Sha Tin',
  'Fo Tan',
  'Ma Liu Shui',
  'Wu Kai Sha',
  'Ma On Shan',
  'Clear Water Bay',
  'Sai Kung',
  'Tai Mong Tsai',
  'Tseung Kwan O',
  'Hang Hau',
  'Tiu Keng Leng',
  'Ma Yau Tong',
  'Cheung Chau',
  'Peng Chau',
  'Lantau Island & Tung Chung',
  'Lamma Island'
];
