
@username = foo
@password = bar
@newPassword = foo

# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}

###

@authToken = {{login.response.body.data.token}}

# @name users
GET {{baseUrl}}/user/list HTTP/1.1
Authorization: bearer {{authToken}}

###

# @name add
POST {{baseUrl}}/user/add HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: bearer {{authToken}}

username={{username}}
&password={{password}}
&role=admin

###

# @name remove
DELETE  {{baseUrl}}/user/remove HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: bearer {{authToken}}

username={{username}}

###

# @name update
PATCH   {{baseUrl}}/user/update HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username={{username}}

###

# @name modify-password
PATCH   {{baseUrl}}/user/modify-password HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&newPassword={{newPassword}}
&confirmNewPassword={{newPassword}}

###