export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

export const USER_MODEL = 'USER_MODEL';

export const REFRESH_TOKEN_MODEL = 'REFRESH_TOKEN_MODEL';

export const PRODUCT_MODEL = 'PRODUCT_MODEL';
